apiVersion: v1
kind: Deployment
metadata:
 name: backend-deployment
 labels:
  app: backend
spec:
  replicas: 3
  
  selectors:
   matchlabels:
    app: backend
  template:
    metadata:
     labels:
      app: backend
    spec:
     containers:
     - name: backend-container
       image: ghcr.io/mahi-oops/backend-app:96
       ports:
       - containerPort: 3000

