apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-app
  labels:
   app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
     app: backend
  template:
    metadata:
      labels:
       app: backend
    spec:
     containers:
     - name: backend-container
       image: ghcr.io/mahi-oops/backend-app:103
       ports:
       - containerPort: 3000

